alias dcp="docker compose pull"
alias dk="docker"
alias dkimg="dk image"
alias dkimgs="dk images"
alias dkl="dk logs"
alias dklf="dkl -f"
alias dkps="dk ps"
alias dkpsa="dk ps -a"
alias dkr="dk run"
alias dkrm="dk rm"
alias dks="dk stop"
alias dkst="dk stats"
alias dps="dk ps -a"

alias alpine="dk run --rm --name alpine -it alpine /bin/sh"
alias ubuntu="dk run --rm --name ubuntu -it ubuntu /bin/bash"
