alias js="node"
alias n=node
alias npmup='npm install -g $(npm ls -g --json | jq -r ".dependencies|keys|join(\" \")")'
alias nrb='nr build'
alias nrd='nr dev'
alias nrf='nr format'
alias nrl='nr lint'
alias nrs='nr start'
alias nrt='nr test'
